### PR TITLE
Fixed UIUX rendering after login and logout

### LINKED ISSUE #119: [BUG] Application not rendering user login sessions and navlinks appropriately.
**Describe the bug**
After logging in, the user in directed to the user dashboard, but when user selects link for landing page, the page incorrectly displays the login and signup forms though even when the user is already logged in.

**To Reproduce**
1. Go to 'sign up, then sign in'
2. Click on 'home link or go back to previous page'
4. See error of displaying the login and sign up forms

**Expected behavior**
After logging in, the user in directed to the user dashboard, then user selects link for landing page, the page still correctly hides the login and signup forms while user already is logged in, navigation links and are rendered appropriately depending on logged in vs non logged in state

**Screenshots**
No screen shots.

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Device: [e.g desktop]
 - Browser [e.g. Firefox 89]

**Additional context**
Tested in the development mode.

### PR DESCRIPTION
**Pull request by drfidel**
## Description
After logging in, the user in directed to the user dashboard, when user selects link for landing page, the page correctly hides/displays the login and signup forms depending on logged in state or logout state.

No new dependencies were required or added.

This fixes this rendering bug after user login and logout.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes#(issue number 119)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.
No UNITTESTS were done to test code, proper rendering was tested using DOM and development features.
the changes made affects mostly the header section of the application jsx code. 

## Screenshots (if applicable, else remove this line / section)
NO SCREEN SHOTS TAKEN

## Checklist:

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mariamiah** [comment]
Thanks for working on this, will have a look at this today 👍🏾

File: src/components/LandingPage.jsx [hunk 1]
```diff
@@ -16,6 +16,14 @@ const LandingPage = () => {
...
     return "Login";
   };
+
+  const checktoken = () => {
+    if (localStorage.getItem("token")) {
+      return true;
+    }
+    return false;
+  };
+
```
Comment (mariamiah) [inline src/components/LandingPage.jsx:26]:
```suggestion
  const checktoken = () => {
    return localStorage.getItem("token")
  };
```

**Review by mariamiah — APPROVED** [review]

File: src/components/LandingPage.jsx (hunk 1 above)
Comment (drfidel) [reply src/components/LandingPage.jsx:26]: Thanks, Noted......will add the change.
